#(1)===================================================================
mu=29321
sigma=2120
n=100
#P(xbar<29000)
xSamp=29000
se=sigma/sqrt(n)
z=(xSamp-mu)/se
z
prob= pnorm(z)
prob

pnorm(29000,mu,se)
#(2)==================================================================
mu1=220
sigma1=15
n1=40
x1=215
se1=sigma1/sqrt(n1)
z1=(x1-mu1)/se1
z1
prob1=pnorm(z1)
prob1

pnorm(215,mu1,se1)
#(3)==================================================================
n=225
xbar=11.6
sd=4.1
qnorm(0.05)
z=qnorm(.95)
z

se=sd/sqrt(n)
ci_lower=xbar-(z*se)
ci_upper=xbar+(z*se)
ci_lower
ci_upper
interval=ci_upper-ci_lower
interval
#4====================================================================
n=100
xbar=49
sd=4.49
z=qnorm(0.95)
z
se=sd/sqrt(n)
ci_lower=xbar-(z*se)
ci_upper=xbar+(z*se)
ci_lower
ci_upper
#5====================================================================
n=100
xbar=1014
sd=25
z=qnorm(0.975)
z
se=sd/sqrt(n)
ci_lower=xbar-(z*se)
ci_upper=xbar+(z*se)
ci_lower
ci_upper
interval=ci_upper-ci_lower
interval
#6====================================================================
p=175/1200
q=1-p
n=1200
z=qnorm(.975)
z
cilow=p-(z*sqrt((p*q)/n))
ciup=p+(z*sqrt((p*q)/n))
cilow
ciup
cilowact=cilow*1200
cilowact
ciupact=ciup*1200
ciupact
#8=========================================================
xbar=9900
sigma=120
n=30
mu=10000
t=(xbar-mu)/(sigma/sqrt(n))
t
qnorm(.05)
#reject the null hypothesis